# Generated by Django 6.0.4 on 2026-04-29 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_rename_category_categories_alter_categories_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sluge", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="featured_images/%Y/%m/%d"
                    ),
                ),
                ("short_description", models.TextField(max_length=500)),
                ("blog_body", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[(0, "Draft"), (1, "Published")],
                        default=0,
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="blogs.categories",
                    ),
                ),
            ],
        ),
    ]
