# Generated by Django 6.0.4 on 2026-04-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_blog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="sluge",
            new_name="slug",
        ),
    ]
